/*
This file has been generated from the list of subjects which are parsed from wikipedia. 
It is needed to prevent the data having to be parsed everytime. 
*/

module.exports = [
  "Agriculture",
  "Architecture and design",
  "Arts",
  "Engineering",
  "Business and management",
  "Computer science and information systems",
  "Health Care",
  "Medicine",
  "Dentistry",
  "Midwifery",
  "Physiotherapy",
  "Optometry",
  "Nursing",
  "Veterinary science",
  "Pharmacy",
  "Public Health",
  "Medical and Health Sciences",
  "Kinesiology",
  "Nutrition and Dietetics",
  "Aviation",
  "Divinity and theology",
  "Fine arts",
  "Film and television",
  "Integrated studies",
  "Journalism",
  "Landscape architecture",
  "Liberal arts",
  "Library science",
  "Music",
  "Mortuary science",
  "Philosophy",
  "Psychology",
  "Education",
  "Science with education",
  "Forestry",
  "Science",
  "Science in law",
  "Social sciences",
  "Social work",
  "Technology",
  "Law",
  "Talmudic law",
  "Tourism studies",
  "Mathematics",
  "Urban and regional planning",
  "Public affairs and policy management",
  "Innovation"
]